# This workflow will upload a Python Package using Twine when a release is created.
# https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries
name: test-only

on: push

jobs:

  test:

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ['3.9', '3.11', '3.13']
      max-parallel: 9
    runs-on: ${{ matrix.os }}
    steps:
      - if: runner.os == 'Linux'
        run: sudo apt-get update -q -q && sudo apt-get install --yes espeak-ng libespeak1
      - if: runner.os == 'macOS'
        run: brew install espeak-ng
      - name: Download and install eSpeak-NG
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://github.com/espeak-ng/espeak-ng/releases/download/1.51/espeak-ng-X64.msi" -OutFile "espeak-ng.msi"
          Start-Process msiexec.exe -ArgumentList '/i espeak-ng.msi /quiet /norestart' -Wait
          # dir "$env:ProgramFiles\eSpeak NG"
          $env:Path += ";$env:ProgramFiles\eSpeak NG"
          espeak-ng --version
      - if: runner.os != 'Windows'
        run: espeak-ng --version

      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pytest
          pip install --editable .

      - timeout-minutes: 15  # Save resources while our pytests are hanging
        run: pytest --full-trace -s -vvv --strict

